# This file was auto-generated by Shut. DO NOT EDIT
# For more information about Shut, check out https://pypi.org/project/shut/

from __future__ import print_function
import io
import os
import setuptools
import sys

readme_file = 'README.md'
if os.path.isfile(readme_file):
  with io.open(readme_file, encoding='utf8') as fp:
    long_description = fp.read()
else:
  print("warning: file \"{}\" does not exist.".format(readme_file), file=sys.stderr)
  long_description = None

requirements = [
  'click',
  'pandas',
  'requests',
  'pytz',
  'python-dateutil',
]

setuptools.setup(
  name = 'solaredge-interface',
  version = '0.1.5',
  author = 'Nicholas de Jong',
  author_email = 'contact@nicholasdejong.com',
  description = 'The SolarEdge Interface provides both a command-line interface and a Python module interface to interact with the SolarEdge API service.',
  long_description = long_description,
  long_description_content_type = 'text/markdown',
  url = 'https://solaredge-interface.readthedocs.io/',
  license = 'MIT',
  packages = setuptools.find_packages('src', ['test', 'test.*', 'tests', 'tests.*', 'docs', 'docs.*']),
  package_dir = {'': 'src'},
  include_package_data = True,
  install_requires = requirements,
  extras_require = {},
  tests_require = [],
  python_requires = '>=3.7.0,<4.0.0',
  data_files = [],
  entry_points = {
    'console_scripts': [
      'solaredge-interface = solaredge_interface.cli.entrypoints:solaredge_interface',
    ]
  },
  cmdclass = {},
  keywords = ['solar', 'solaredge', 'solaredge api', 'solaredge interface'],
  classifiers = ['Environment :: Console', 'Intended Audience :: Developers', 'Intended Audience :: Information Technology', 'Programming Language :: Python :: 3.7', 'Programming Language :: Python :: 3.8', 'License :: OSI Approved :: MIT License'],
  zip_safe = True,
)
